/**
 * Hotel Seed Script - Popular Sri Lankan Hotels
 * Removes all existing hotels and inserts curated Sri Lankan hotel data
 * 
 * Usage: node database/seeders/seedHotels.js
 */

const path = require('path');

// Resolve paths relative to server directory
const serverDir = path.join(__dirname, '../../server');
module.paths.unshift(path.join(serverDir, 'node_modules'));

require('dotenv').config({ path: path.join(serverDir, '.env') });
const sequelize = require(path.join(serverDir, 'config/database'));
const Hotel = require(path.join(serverDir, 'hotel-accommodation-management/models/Hotel'));

const sriLankanHotels = [
  // ===== COLOMBO (5 hotels) =====
  {
    hotel_name: 'Shangri-La Hotel Colombo',
    hotel_description: 'Shangri-La Hotel Colombo is a luxury 5-star hotel located along the iconic Galle Face waterfront. The hotel features 500 elegantly appointed rooms and suites with stunning ocean views, world-class dining at multiple restaurants including Shang Palace for authentic Chinese cuisine, Capital Bar & Grill, and Table One for international flavors. Guests enjoy a spectacular infinity pool, luxury spa, and state-of-the-art fitness center.',
    star_classification: '5-star',
    hotel_classification: 'Hotel',
    hotel_address: '1 Galle Face, Colombo 02, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Colombo',
    micro_location: 'Galle Face',
    hotel_status: '1',
    markup: 89600,
    sub_description: 'Luxury waterfront hotel on Galle Face promenade with panoramic Indian Ocean views',
    longitude: '79.8447',
    latitude: '6.9271',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Cinnamon Grand Colombo',
    hotel_description: 'A landmark in the heart of Colombo, Cinnamon Grand is the city\'s largest 5-star hotel with 501 rooms and suites. Located on Galle Road overlooking the Indian Ocean, it offers 14 dining experiences ranging from authentic Sri Lankan cuisine to Japanese teppanyaki. The hotel features a lagoon-style pool, full-service spa, modern gym, and is a short walk from shopping and entertainment.',
    star_classification: '5-star',
    hotel_classification: 'Hotel',
    hotel_address: '77 Galle Road, Colombo 03, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Colombo',
    micro_location: 'Kollupitiya',
    hotel_status: '1',
    markup: 62400,
    sub_description: 'Iconic 5-star landmark hotel in the heart of Colombo with 14 restaurants',
    longitude: '79.8500',
    latitude: '6.9100',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Hilton Colombo',
    hotel_description: 'Hilton Colombo is a prestigious 5-star hotel situated in the commercial heart of the city next to the World Trade Center. The hotel offers 382 well-appointed rooms with city or harbor views, an executive floor with private lounge, outdoor pool surrounded by tropical gardens, comprehensive fitness center, and multiple award-winning restaurants including Curry Leaf for authentic Sri Lankan cuisine.',
    star_classification: '5-star',
    hotel_classification: 'Hotel',
    hotel_address: '2 Sir Chittampalam A. Gardiner Mawatha, Colombo 02, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Colombo',
    micro_location: 'Fort',
    hotel_status: '1',
    markup: 56000,
    sub_description: 'Premium business hotel in Colombo Fort with harbor views and executive facilities',
    longitude: '79.8440',
    latitude: '6.9340',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Kingsbury Hotel Colombo',
    hotel_description: 'The Kingsbury is a sophisticated 5-star urban resort overlooking the Colombo harbor. With 229 luxurious rooms and suites, rooftop bar with stunning city views, multiple fine dining restaurants, an outdoor infinity pool, and world-class wellness spa, it represents the pinnacle of modern Sri Lankan hospitality in a heritage-rich setting.',
    star_classification: '5-star',
    hotel_classification: 'Hotel',
    hotel_address: '48 Janadhipathi Mawatha, Colombo 01, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Colombo',
    micro_location: 'Fort',
    hotel_status: '1',
    markup: 52800,
    sub_description: 'Elegant urban resort with harbor views and rooftop dining in Colombo Fort',
    longitude: '79.8410',
    latitude: '6.9355',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Mövenpick Hotel Colombo',
    hotel_description: 'Mövenpick Hotel Colombo offers a modern and vibrant 5-star experience in the heart of the city. The hotel features 219 contemporary rooms, signature Swiss hospitality, AYU - the rooftop bar and lounge, Vistas restaurant with live cooking stations, an outdoor pool, and a fully equipped fitness center. Perfect for both business and leisure travelers.',
    star_classification: '5-star',
    hotel_classification: 'Hotel',
    hotel_address: '24 Dharmapala Mawatha, Colombo 03, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Colombo',
    micro_location: 'Colombo 03',
    hotel_status: '1',
    markup: 49600,
    sub_description: 'Modern Swiss-inspired luxury hotel with rooftop bar and vibrant dining',
    longitude: '79.8561',
    latitude: '6.9110',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== KANDY (4 hotels) =====
  {
    hotel_name: 'Cinnamon Citadel Kandy',
    hotel_description: 'Nestled along the banks of the Mahaweli River, Cinnamon Citadel Kandy offers a serene escape in Sri Lanka\'s cultural capital. The 4-star hotel features 121 rooms with river or mountain views, an outdoor pool overlooking the Mahaweli, Panorama restaurant with breathtaking views, and easy access to the Temple of the Sacred Tooth Relic and Peradeniya Botanical Gardens.',
    star_classification: '4-star',
    hotel_classification: 'Hotel',
    hotel_address: '124 Srimath Kuda Ratwatte Mawatha, Kandy, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Kandy',
    micro_location: 'Mahaweli River',
    hotel_status: '1',
    markup: 35200,
    sub_description: 'Riverside 4-star hotel near Temple of the Tooth with Mahaweli River views',
    longitude: '80.6332',
    latitude: '7.2916',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Earl\'s Regency Hotel',
    hotel_description: 'Earl\'s Regency is a luxury 5-star hotel located just outside Kandy, surrounded by lush tropical hills. The hotel features 120 rooms with valley views, a stunning outdoor pool perched on a hillside, award-winning spa, fine dining at multiple restaurants, and is perfectly located for exploring Kandy\'s cultural heritage sites including the Temple of the Tooth.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Kundasale, Kandy, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Kandy',
    micro_location: 'Kundasale',
    hotel_status: '1',
    markup: 46400,
    sub_description: 'Hillside luxury resort with valley views near Kandy cultural sites',
    longitude: '80.6640',
    latitude: '7.3010',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Mahaweli Reach Hotel',
    hotel_description: 'Mahaweli Reach Hotel is a charming 4-star property set on the banks of the Mahaweli River in the heart of Kandy. Offering 112 rooms, a riverside swimming pool, tennis courts, and multiple dining options, it provides an ideal base for exploring the UNESCO World Heritage city of Kandy and its surrounding tea country.',
    star_classification: '4-star',
    hotel_classification: 'Hotel',
    hotel_address: '35 P.B.A. Weerakoon Mawatha, Kandy, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Kandy',
    micro_location: 'City Center',
    hotel_status: '1',
    markup: 30400,
    sub_description: 'Riverside hotel in the heart of Kandy with pool and cultural heritage access',
    longitude: '80.6420',
    latitude: '7.2950',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'The Radh Hotel Kandy',
    hotel_description: 'A boutique luxury hotel offering an intimate retreat in the hills of Kandy. With just 10 beautifully designed suites, each featuring private balconies with stunning mountain views, personalized butler service, farm-to-table dining, infinity pool, and spa treatments, The Radh provides an exclusive and memorable Sri Lankan hill country experience.',
    star_classification: '5-star',
    hotel_classification: 'Boutique',
    hotel_address: 'Heerassagala, Kandy, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Kandy',
    micro_location: 'Heerassagala',
    hotel_status: '1',
    markup: 70400,
    sub_description: 'Exclusive boutique hotel with 10 suites and private mountain views in Kandy hills',
    longitude: '80.6100',
    latitude: '7.2750',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== GALLE (4 hotels) =====
  {
    hotel_name: 'Amangalla',
    hotel_description: 'Amangalla is an iconic luxury hotel housed within the historic Galle Fort, a UNESCO World Heritage Site. Originally the New Oriental Hotel established in 1863, it has been meticulously restored to blend colonial grandeur with Aman\'s minimalist elegance. Features 30 suites, a garden pool, Baths spa with hydrotherapy, and fine dining showcasing local cuisine.',
    star_classification: '5-star',
    hotel_classification: 'Boutique',
    hotel_address: '10 Church Street, Galle Fort, Galle, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Galle',
    micro_location: 'Galle Fort',
    hotel_status: '1',
    markup: 144000,
    sub_description: 'Historic luxury hotel inside UNESCO Galle Fort, blending colonial elegance with Aman style',
    longitude: '80.2170',
    latitude: '6.0300',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Jetwing Lighthouse',
    hotel_description: 'Designed by the legendary Geoffrey Bawa, Jetwing Lighthouse is an architectural masterpiece perched on a rocky outcrop overlooking the Indian Ocean. The 5-star hotel features 63 rooms, a spectacular ocean-view pool, spa, several dining venues including Cardamom Café, and is just a short distance from the historic Galle Fort.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Dadella, Galle, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Galle',
    micro_location: 'Dadella',
    hotel_status: '1',
    markup: 59200,
    sub_description: 'Geoffrey Bawa-designed oceanfront masterpiece near Galle Fort',
    longitude: '80.2090',
    latitude: '6.0150',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'The Fortress Resort & Spa',
    hotel_description: 'The Fortress Resort & Spa is a luxurious beachfront retreat located on the pristine coast of Koggala near Galle. With 53 spacious rooms and suites, beach access, two swimming pools, a renowned spa, and fine dining at its restaurants, this 5-star resort offers a perfect blend of beach relaxation and cultural exploration.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Koggala, Galle, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1573052905904-34ad8c27f0cc?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Galle',
    micro_location: 'Koggala',
    hotel_status: '1',
    markup: 67200,
    sub_description: 'Beachfront luxury resort in Koggala with dual pools and spa near Galle',
    longitude: '80.3130',
    latitude: '5.9870',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Fort Bazaar Galle',
    hotel_description: 'Fort Bazaar is a stylish boutique hotel nestled within the walls of Galle Fort. This beautifully restored 17th-century merchant\'s house features 18 individually designed rooms, a charming courtyard, rooftop terrace with fort views, Church Street Social restaurant, and a relaxing spa. Walking distance to all Galle Fort attractions.',
    star_classification: '4-star',
    hotel_classification: 'Boutique',
    hotel_address: '26 Church Street, Galle Fort, Galle, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Galle',
    micro_location: 'Galle Fort',
    hotel_status: '1',
    markup: 54400,
    sub_description: 'Stylish boutique hotel in a restored 17th-century building inside Galle Fort',
    longitude: '80.2175',
    latitude: '6.0290',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== ELLA (3 hotels) =====
  {
    hotel_name: '98 Acres Resort & Spa',
    hotel_description: '98 Acres Resort and Spa is a breathtaking eco-luxury resort situated on 98 acres of lush tea estate in Ella. The resort offers 40 chalets with floor-to-ceiling windows framing Little Adam\'s Peak and Ella Rock. Featuring an infinity pool overlooking the valley, spa, organic restaurant, and guided tea estate walks, it\'s the ultimate hill country retreat.',
    star_classification: '4-star',
    hotel_classification: 'Resort',
    hotel_address: 'Ella-Passara Road, Ella, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Ella',
    micro_location: 'Tea Estate',
    hotel_status: '1',
    markup: 43200,
    sub_description: 'Eco-luxury resort on 98 acres of tea estate with views of Little Adam\'s Peak',
    longitude: '81.0465',
    latitude: '6.8667',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Ella Jungle Resort',
    hotel_description: 'Ella Jungle Resort is an eco-friendly hideaway set deep within the lush tropical hills of Ella. Offering rustic-luxury wooden cabins surrounded by jungle, mountain-view dining, natural stream pools, guided jungle treks, and spectacular sunrise viewpoints. Perfect for nature lovers seeking an authentic off-the-grid Sri Lankan experience.',
    star_classification: '3-star',
    hotel_classification: 'Resort',
    hotel_address: 'Kithalella, Ella, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1618245318763-a15156d6b23c?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Ella',
    micro_location: 'Kithalella',
    hotel_status: '1',
    markup: 20800,
    sub_description: 'Eco-friendly jungle retreat with rustic cabins and natural stream pools in Ella',
    longitude: '81.0500',
    latitude: '6.8550',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Mountain Heavens Ella',
    hotel_description: 'Mountain Heavens is a charming boutique property perched on the mountain slopes of Ella, offering panoramic views of the surrounding hills and valleys. With 15 well-appointed rooms, a scenic restaurant serving local and international cuisine, garden terrace, and proximity to Nine Arches Bridge and Ravana Falls, it\'s ideal for hill country exploration.',
    star_classification: '3-star',
    hotel_classification: 'Boutique',
    hotel_address: 'Passara Road, Ella, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Ella',
    micro_location: 'Passara Road',
    hotel_status: '1',
    markup: 17600,
    sub_description: 'Mountainside boutique hotel with panoramic views near Nine Arches Bridge',
    longitude: '81.0470',
    latitude: '6.8690',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== NEGOMBO (3 hotels) =====
  {
    hotel_name: 'Heritance Negombo',
    hotel_description: 'Heritance Negombo is a stunning 5-star beachfront resort designed by renowned architect Geoffrey Bawa. Located on the golden sands of Negombo beach, just 15 minutes from Bandaranaike International Airport, it features 141 rooms, a 100-meter ocean-facing pool, Olu spa, multiple restaurants, and lush tropical gardens.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Ethukala, Negombo, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Negombo',
    micro_location: 'Ethukala Beach',
    hotel_status: '1',
    markup: 51200,
    sub_description: 'Bawa-designed beachfront resort 15 min from airport with 100m ocean pool',
    longitude: '79.8380',
    latitude: '7.2230',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Jetwing Beach Negombo',
    hotel_description: 'Jetwing Beach is a premium 5-star resort on the sun-kissed shores of Negombo. Originally designed by Geoffrey Bawa and recently renovated, it offers 78 modern rooms, a stunning beachfront pool, Sands restaurant for seafood, Black Coral Spa, water sports, and easy airport access. The perfect start or end to any Sri Lanka journey.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Ethukala, Negombo, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1586611292717-f828b167408c?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Negombo',
    micro_location: 'Ethukala Beach',
    hotel_status: '1',
    markup: 48000,
    sub_description: 'Premium beachfront resort by Geoffrey Bawa with seafood dining near airport',
    longitude: '79.8370',
    latitude: '7.2250',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Goldi Sands Hotel',
    hotel_description: 'Goldi Sands Hotel is a popular 3-star beachfront hotel in Negombo, offering excellent value with direct beach access, a large outdoor pool, comfortable rooms with ocean views, a multi-cuisine restaurant, and a convenient location just 10 minutes from the airport. Ideal for budget-conscious travelers who want a beachside stay.',
    star_classification: '3-star',
    hotel_classification: 'Hotel',
    hotel_address: 'Ethukala, Negombo, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Negombo',
    micro_location: 'Ethukala Beach',
    hotel_status: '1',
    markup: 17600,
    sub_description: 'Value beachfront hotel near airport with pool and ocean views',
    longitude: '79.8375',
    latitude: '7.2240',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== NUWARA ELIYA (3 hotels) =====
  {
    hotel_name: 'Heritance Tea Factory',
    hotel_description: 'Heritance Tea Factory is a unique 5-star hotel converted from a century-old tea factory in the misty hills of Nuwara Eliya. Perched at 2,200m elevation, it retains original factory machinery as décor. Offering 57 rooms, a tea-themed restaurant, spa, guided tea plucking tours, and stunning views of rolling tea plantations, it provides an unforgettable hill country experience.',
    star_classification: '5-star',
    hotel_classification: 'Boutique',
    hotel_address: 'Kandapola, Nuwara Eliya, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1585543805890-6051f7829f98?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Nuwara Eliya',
    micro_location: 'Kandapola',
    hotel_status: '1',
    markup: 56000,
    sub_description: 'Unique 5-star hotel in a converted tea factory at 2,200m with plantation views',
    longitude: '80.7120',
    latitude: '6.9900',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Grand Hotel Nuwara Eliya',
    hotel_description: 'The Grand Hotel is a colonial-era icon originally built in 1891 as the residence of the Governor of Ceylon. This 4-star heritage hotel features 154 rooms with English-country styling, manicured gardens, Barnes Hall restaurant, a classic billiards room, indoor heated pool, and is walking distance to Nuwara Eliya town center and Victoria Park.',
    star_classification: '4-star',
    hotel_classification: 'Hotel',
    hotel_address: 'Grand Hotel Road, Nuwara Eliya, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Nuwara Eliya',
    micro_location: 'Town Center',
    hotel_status: '1',
    markup: 38400,
    sub_description: 'Colonial-era 1891 heritage hotel in Little England with English gardens',
    longitude: '80.7670',
    latitude: '6.9700',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Araliya Green Hills Hotel',
    hotel_description: 'Araliya Green Hills is a modern 4-star hotel set amidst the cool, misty hills of Nuwara Eliya. With 160 rooms offering mountain and garden views, an indoor heated pool, spa and wellness center, kids\' play area, multiple restaurants, and beautiful landscaped gardens, it provides a comfortable and family-friendly hill country retreat.',
    star_classification: '4-star',
    hotel_classification: 'Hotel',
    hotel_address: '3 Unique View Road, Nuwara Eliya, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1561501900-3701fa6a0864?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Nuwara Eliya',
    micro_location: 'Unique View',
    hotel_status: '1',
    markup: 33600,
    sub_description: 'Modern family-friendly hotel in the misty hills with indoor heated pool',
    longitude: '80.7650',
    latitude: '6.9680',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== MIRISSA (2 hotels) =====
  {
    hotel_name: 'Anantara Peace Haven Tangalle',
    hotel_description: 'Anantara Peace Haven is a stunning 5-star resort on the golden beach of Tangalle in the deep south. Featuring 152 rooms and villas with private pools, a magnificent cliffside infinity pool, Anantara Spa with Ayurvedic treatments, water sports, whale watching excursions, and multiple world-class restaurants with ocean views.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Goyambokka Estate, Tangalle, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Mirissa',
    micro_location: 'Tangalle Coast',
    hotel_status: '1',
    markup: 102400,
    sub_description: 'Clifftop luxury resort with private pool villas and Ayurvedic spa on the south coast',
    longitude: '80.8040',
    latitude: '6.0100',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Mirissa Hills Boutique Hotel',
    hotel_description: 'Mirissa Hills is a peaceful boutique retreat on the hillside overlooking the legendary Mirissa beach. With just 8 uniquely styled rooms, a saltwater infinity pool with ocean views, open-air restaurant serving fresh seafood, yoga deck, and personalized service, it offers an intimate tropical escape perfect for couples and solo travelers.',
    star_classification: '3-star',
    hotel_classification: 'Boutique',
    hotel_address: 'Mirissa Hills Road, Mirissa, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Mirissa',
    micro_location: 'Mirissa Hills',
    hotel_status: '1',
    markup: 27200,
    sub_description: 'Intimate hillside boutique hotel overlooking Mirissa beach with infinity pool',
    longitude: '80.4540',
    latitude: '5.9480',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== BENTOTA (2 hotels) =====
  {
    hotel_name: 'Vivanta by Taj Bentota',
    hotel_description: 'Vivanta by Taj is a premium 5-star beach resort in Bentota, offering 160 rooms and suites with gorgeous ocean views. The resort features a large beachfront pool, Jiva Spa with Ayurvedic treatments, water sports center for kayaking and jet skiing, multiple restaurants, and beautiful tropical gardens along the golden Bentota beach.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'National Holiday Resort, Bentota, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Bentota',
    micro_location: 'Bentota Beach',
    hotel_status: '1',
    markup: 62400,
    sub_description: 'Premium beach resort with Ayurvedic spa and water sports on Bentota\'s golden coast',
    longitude: '79.9980',
    latitude: '6.4280',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Club Bentota',
    hotel_description: 'Club Bentota is a charming 3-star resort located on a narrow peninsula between the Bentota lagoon and the Indian Ocean. Designed by Geoffrey Bawa, it offers 133 rooms with lagoon or ocean views, two swimming pools, water sports on both the lagoon and sea, and a relaxed tropical atmosphere perfect for a beach holiday on a budget.',
    star_classification: '3-star',
    hotel_classification: 'Resort',
    hotel_address: 'Bentota, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Bentota',
    micro_location: 'Bentota Lagoon',
    hotel_status: '1',
    markup: 22400,
    sub_description: 'Bawa-designed resort on a peninsula between Bentota lagoon and Indian Ocean',
    longitude: '79.9970',
    latitude: '6.4260',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== SIGIRIYA / DAMBULLA (2 hotels) =====
  {
    hotel_name: 'Heritance Kandalama',
    hotel_description: 'Heritance Kandalama is a legendary 5-star hotel designed by Geoffrey Bawa, built into a cliff face overlooking the Kandalama reservoir with Sigiriya Rock visible in the distance. The hotel features 152 rooms camouflaged in the jungle canopy, two infinity pools, a cave-like spa, nature trails, and birdwatching. A masterpiece of eco-architecture.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Kandalama, Dambulla, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1615880484746-a134be9a6ecf?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Dambulla',
    micro_location: 'Kandalama',
    hotel_status: '1',
    markup: 60800,
    sub_description: 'Iconic Bawa-designed jungle hotel overlooking Kandalama reservoir and Sigiriya',
    longitude: '80.7250',
    latitude: '7.8780',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
  {
    hotel_name: 'Aliya Resort & Spa Sigiriya',
    hotel_description: 'Aliya Resort & Spa is a modern 4-star resort inspired by the majestic Sri Lankan elephant. Located near the ancient Sigiriya Rock Fortress, it offers 100 spacious rooms, a stunning elephant-shaped infinity pool, Ayurvedic spa, nature excursions, and panoramic views of the Cultural Triangle. Perfect base for exploring Sigiriya, Pidurangala, and Dambulla.',
    star_classification: '4-star',
    hotel_classification: 'Resort',
    hotel_address: 'Sigiriya Road, Sigiriya, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Dambulla',
    micro_location: 'Sigiriya',
    hotel_status: '1',
    markup: 38400,
    sub_description: 'Elephant-inspired resort near Sigiriya Rock with unique infinity pool',
    longitude: '80.7590',
    latitude: '7.9520',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== TRINCOMALEE (1 hotel) =====
  {
    hotel_name: 'Jungle Beach by Uga Escapes',
    hotel_description: 'Jungle Beach by Uga Escapes is an exclusive 5-star eco-resort hidden in the jungle overlooking the pristine Kuchchaveli beach near Trincomalee. With 48 villas and cabins nestled among the trees, private beach access, nature-inspired pool, spa, snorkeling, and dive center for exploring Pigeon Island, it\'s the ultimate tropical wilderness escape.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Kuchchaveli, Trincomalee, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1499793983394-12903e570d0e?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Trincomalee',
    micro_location: 'Kuchchaveli',
    hotel_status: '1',
    markup: 80000,
    sub_description: 'Exclusive jungle eco-resort with private beach and diving near Pigeon Island',
    longitude: '81.1900',
    latitude: '8.6500',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },

  // ===== YALA (1 hotel) =====
  {
    hotel_name: 'Wild Coast Tented Lodge Yala',
    hotel_description: 'Wild Coast Tented Lodge is a luxury glamping experience on the edge of Yala National Park. Inspired by leopard cocoons, the 36 tented structures feature plunge pools, outdoor showers, and ocean views. Includes guided safari drives into Yala to spot leopards and elephants, a stunning pool, spa treatments, and gourmet dining under the stars.',
    star_classification: '5-star',
    hotel_classification: 'Resort',
    hotel_address: 'Palatupana, Yala, Sri Lanka',
    hotel_image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
    country: 'Sri Lanka',
    city: 'Yala',
    micro_location: 'Palatupana',
    hotel_status: '1',
    markup: 121600,
    sub_description: 'Luxury glamping lodge by Yala National Park with leopard safari drives',
    longitude: '81.5350',
    latitude: '6.2680',
    provider: 'PathFinderSL',
    auto_confirmation: 1,
  },
];

async function seedHotels() {
  try {
    console.log('🔌 Connecting to database...');
    await sequelize.authenticate();
    console.log('✅ Database connected successfully\n');

    // Count existing hotels
    const existingCount = await Hotel.count({ paranoid: false });
    console.log(`📊 Found ${existingCount} existing hotels in database`);

    // Hard delete all existing hotels (including soft-deleted)
    console.log('🗑️  Removing all existing hotels...');
    await sequelize.query('DELETE FROM hotels');
    await sequelize.query('ALTER TABLE hotels AUTO_INCREMENT = 1');
    console.log('✅ All hotels removed and auto-increment reset\n');

    // Insert new hotels
    console.log(`🏨 Inserting ${sriLankanHotels.length} curated Sri Lankan hotels...\n`);

    for (let i = 0; i < sriLankanHotels.length; i++) {
      const hotel = sriLankanHotels[i];
      await Hotel.create(hotel);
      console.log(`  ✅ [${i + 1}/${sriLankanHotels.length}] ${hotel.hotel_name} (${hotel.city})`);
    }

    // Verify
    const newCount = await Hotel.count();
    console.log(`\n🎉 Seeding complete! ${newCount} hotels now in database.`);

    // Summary by city
    const [citySummary] = await sequelize.query(
      `SELECT city, COUNT(*) as count, GROUP_CONCAT(star_classification SEPARATOR ', ') as stars 
       FROM hotels WHERE deleted_at IS NULL GROUP BY city ORDER BY count DESC`
    );
    console.log('\n📍 Hotels by city:');
    citySummary.forEach(row => {
      console.log(`   ${row.city}: ${row.count} hotels`);
    });

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
}

seedHotels();

